### ISSUE TITLE
[Feature Request]: Dark Matter Explosive

### ISSUE THREAD

**Issue by buithanh12072001** [aidancbrady/DefenseTech#17]
I think you should add some devastating explosive called Dark Matter. It may create a black hole bigger than Redmatter and it is the combination of antimatter and red matter.

**Comment by Robot-Gentleman** [comment]
Also a dark energy bomb would be awesome, it would be a reverse red matter/dark matter bomb because dark energy is expanding the universe outwards constantly so a dark energy bomb would push stuff away. You could use that as the basis of your force-field mod. The dark energy could be used to form bombs that just shove stuff away constantly and the force-fields could be directed forms of it.

**Comment by SupernovaCo** [comment]
Interesting idea! I quite like it!

**Comment by Robot-Gentleman** [comment]
Also that could be used for an end game turret if turrets are ever added. Also grenades that would work to repel people with gravity bombs. This is starting to sound like a separate mod based on gravity kind of.

**Comment by buithanh12072001** [comment]
The ''dark matter'' not only creates a big hole like antimatter, but it also creates a black hole. I think only antimatter can penetrate it.

**Comment by aidancbrady** [comment]
I'm going to be sticking with Antimatter and Red Matter as the two primary T4 explosions for now, at least until we get the foundation of the mod complete.  I'll take a look when I have time later.
