### ISSUE TITLE
The EMP doesn't work with Thermal Expansion

### ISSUE THREAD

**Issue by Robot-Gentleman** [aidancbrady/DefenseTech#7]
I have tried using it near all types of energy cells and devices from thermal expansion storing RF. Also not sure if this is a bug but it doesn't disable electronics like the old mod, it just drains the RF. Also I am pretty sure in the old mod nukes would disable electronics too like real EMPs. (Also where do I put suggestions for the mod?)

**Comment by aidancbrady** [comment]
This is due to TE not having an easy way of setting energy values.  I'm afraid this may be unfixable without reflection- perhaps I could try and manage something later.

If you have a well-thought-out feature request you can just put it on GitHub and I'll tag it accordingly. Just make sure the report is detailed.
